/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bugsnax Server API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.bugsnaxapp.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id The id of the bugsnak
 * @property location
 * @property name The name of the Bugsnak
 */
@JsonClass(generateAdapter = true)
data class Bugsnak(
    @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
    @Json(name = "location") @field:Json(name = "location") var location: BugsnakLocation? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null
)
