/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bugsnax Server API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.bugsnaxapp.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property fears
 * @property hates
 * @property id The id of the grumpus
 * @property locations
 * @property loves
 * @property name The name of the grumpus
 * @property occupation The current occupation of the grumpus
 */
@JsonClass(generateAdapter = true)
data class Grumpus(
    @Json(name = "fears") @field:Json(name = "fears") var fears: List<LocationInhabitants>? = null,
    @Json(name = "hates") @field:Json(name = "hates") var hates: List<LocationInhabitants>? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
    @Json(name = "locations") @field:Json(name = "locations") var locations: List<BugsnakLocation>? = null,
    @Json(name = "loves") @field:Json(name = "loves") var loves: List<LocationInhabitants>? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "occupation") @field:Json(name = "occupation") var occupation: String? = null
)
