/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bugsnax Server API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.bugsnaxapp.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property bugsnax
 * @property id The id of the location
 * @property inhabitants
 * @property name The name of the location
 */
@JsonClass(generateAdapter = true)
data class Location(
    @Json(name = "bugsnax") @field:Json(name = "bugsnax") var bugsnax: List<LocationBugsnax>? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
    @Json(name = "inhabitants") @field:Json(name = "inhabitants") var inhabitants: List<LocationInhabitants>? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null
)
