/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bugsnax Server API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.bugsnaxapp.client.apis

import hu.bme.aut.bugsnaxapp.client.models.Bugsnak
import hu.bme.aut.bugsnaxapp.client.models.InlineResponse200
import io.reactivex.rxjava3.core.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface BugsnaxApi {
    /**
     * Find a bugsnak by its id
     * The endpoint is owned by defaultname service owner
     * @param id The id of the bugsnak (required)
     */
    @Headers(
        "X-Operation-ID: GetBugsnakById"
    )
    @GET("bugsnax/{id}")
    fun getBugsnakById(
        @retrofit2.http.Path("id") id: Int
    ): Single<Bugsnak>
    /**
     * Returns all bugsnax
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: GetBugsnax"
    )
    @GET("bugsnax")
    fun getBugsnax(): Single<InlineResponse200>
}
