/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bugsnax Server API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.bugsnaxapp.client.apis

import hu.bme.aut.bugsnaxapp.client.models.Grumpus
import hu.bme.aut.bugsnaxapp.client.models.InlineResponse2002
import io.reactivex.rxjava3.core.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface GrumpusesApi {
    /**
     * Find a grumpus by its id
     * The endpoint is owned by defaultname service owner
     * @param id The id of the grumpus (required)
     */
    @Headers(
        "X-Operation-ID: GetGrumpusById"
    )
    @GET("grumpuses/{id}")
    fun getGrumpusById(
        @retrofit2.http.Path("id") id: Int
    ): Single<Grumpus>
    /**
     * Returns all grumpuses
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: GetGrumpuses"
    )
    @GET("grumpuses")
    fun getGrumpuses(): Single<InlineResponse2002>
}
