/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bugsnax Server API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.bugsnaxapp.client.apis

import hu.bme.aut.bugsnaxapp.client.models.InlineResponse2001
import hu.bme.aut.bugsnaxapp.client.models.Location
import io.reactivex.rxjava3.core.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface LocationsApi {
    /**
     * Find a location by its id
     * The endpoint is owned by defaultname service owner
     * @param id The id of the location (required)
     */
    @Headers(
        "X-Operation-ID: GetLocationById"
    )
    @GET("locations/{id}")
    fun getLocationById(
        @retrofit2.http.Path("id") id: Int
    ): Single<Location>
    /**
     * Returns all locations
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: GetLocations"
    )
    @GET("locations")
    fun getLocations(): Single<InlineResponse2001>
}
